import { type NextRequest, NextResponse } from "next/server";
import { generatePortfolioHTML } from "@/lib/export/generate-html";
import type { PortfolioData, DesignPreferences, StrategicFocus } from "@/lib/types/portfolio";

export const dynamic = "force-dynamic";

interface DeployPayload {
  portfolio: PortfolioData;
  design: DesignPreferences;
  strategy: StrategicFocus;
  repoName?: string;
}

interface GitHubUser {
  login: string;
}

interface GitHubRepo {
  name: string;
  full_name: string;
  html_url: string;
}

interface GitHubFileContent {
  sha?: string;
}

async function githubFetch(
  path: string,
  token: string,
  options: RequestInit = {}
): Promise<Response> {
  return fetch(`https://api.github.com${path}`, {
    ...options,
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: "application/vnd.github+json",
      "X-GitHub-Api-Version": "2022-11-28",
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
}

export async function POST(request: NextRequest): Promise<NextResponse> {
  const token = request.cookies.get("gh_token")?.value;
  if (!token) {
    return NextResponse.json({ error: "not_authenticated" }, { status: 401 });
  }

  let payload: DeployPayload;
  try {
    payload = (await request.json()) as DeployPayload;
  } catch {
    return NextResponse.json({ error: "Invalid JSON body." }, { status: 400 });
  }

  const { portfolio, design, strategy, repoName: rawRepoName } = payload;

  // 1. Get the authenticated user
  const userRes = await githubFetch("/user", token);
  if (!userRes.ok) {
    return NextResponse.json({ error: "Failed to fetch GitHub user." }, { status: 502 });
  }
  const user = (await userRes.json()) as GitHubUser;
  // Sanitize repo name: lowercase, alphanumeric + hyphens, max 100 chars
  const repoName = (rawRepoName ?? "pm-portfolio")
    .toLowerCase()
    .replace(/[^a-z0-9-]/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 100) || "pm-portfolio";

  // 2. Create repo (idempotent — ignore 422 if it already exists)
  const createRes = await githubFetch("/user/repos", token, {
    method: "POST",
    body: JSON.stringify({
      name: repoName,
      description: `${user.login}'s PM Portfolio — generated by PM Portfolio Builder`,
      private: false,
      auto_init: true,
    }),
  });

  let repo: GitHubRepo;
  if (createRes.status === 422) {
    // Repo already exists — fetch it
    const existingRes = await githubFetch(`/repos/${user.login}/${repoName}`, token);
    if (!existingRes.ok) {
      return NextResponse.json({ error: "Failed to access existing repo." }, { status: 502 });
    }
    repo = (await existingRes.json()) as GitHubRepo;
  } else if (!createRes.ok) {
    return NextResponse.json({ error: "Failed to create GitHub repo." }, { status: 502 });
  } else {
    repo = (await createRes.json()) as GitHubRepo;
    // Brief pause to let auto_init complete
    await new Promise((r) => setTimeout(r, 1500));
  }

  // 3. Generate HTML
  const html = generatePortfolioHTML(portfolio, design, strategy);
  const content = Buffer.from(html).toString("base64");

  // 4. Check if index.html already exists (to get its SHA for update)
  const existingFileRes = await githubFetch(
    `/repos/${user.login}/${repoName}/contents/index.html`,
    token
  );
  let existingSha: string | undefined;
  if (existingFileRes.ok) {
    const existing = (await existingFileRes.json()) as GitHubFileContent;
    existingSha = existing.sha;
  }

  // 5. Create or update index.html
  const fileBody: Record<string, string> = {
    message: "Update portfolio via PM Portfolio Builder",
    content,
  };
  if (existingSha) fileBody["sha"] = existingSha;

  const fileRes = await githubFetch(
    `/repos/${user.login}/${repoName}/contents/index.html`,
    token,
    { method: "PUT", body: JSON.stringify(fileBody) }
  );

  if (!fileRes.ok) {
    return NextResponse.json({ error: "Failed to push index.html." }, { status: 502 });
  }

  // 6. Enable GitHub Pages (idempotent — ignore 409 conflict if already enabled)
  const pagesRes = await githubFetch(`/repos/${user.login}/${repoName}/pages`, token, {
    method: "POST",
    body: JSON.stringify({ source: { branch: "main", path: "/" } }),
  });

  const pagesOk = pagesRes.ok || pagesRes.status === 409;
  if (!pagesOk) {
    // Pages failed but the file was pushed — return partial success
    return NextResponse.json({
      url: repo.html_url,
      pagesUrl: null,
      warning: "GitHub Pages could not be enabled automatically. Enable it in repo Settings → Pages.",
    });
  }

  const pagesUrl = `https://${user.login}.github.io/${repoName}/`;

  return NextResponse.json({ url: repo.html_url, pagesUrl });
}
